on: 
  issue_comment:
    types: [created]

name: Show cards in Github issues

jobs:
  extract-image:
    name: Extract image
    runs-on: ubuntu-latest
    steps:
     - uses: actions/github-script@v6
       with:
          script: |
            console.log(JSON.stringify(context, null, 2))
